
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 27 2024 19:48:41 IST (Mar 27 2024 14:18:41 UTC)

// Verification Directory fv/rca 

module rca(clk_i, rst_i, a_i, b_i, c_i, s_o, c_o, SE, scan_in,
     scan_out);
  input clk_i, rst_i, c_i, SE, scan_in;
  input [3:0] a_i, b_i;
  output [3:0] s_o;
  output c_o, scan_out;
  wire clk_i, rst_i, c_i, SE, scan_in;
  wire [3:0] a_i, b_i;
  wire [3:0] s_o;
  wire c_o, scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  assign scan_out = c_o;
  SDFFQX1 \genblk2[3].reg_s_q_o_reg (.CK (clk_i), .D (n_12), .SI
       (s_o[2]), .SE (SE), .Q (s_o[3]));
  SDFFQX1 reg_c_q_o_reg(.CK (clk_i), .D (n_11), .SI (s_o[3]), .SE (SE),
       .Q (c_o));
  NOR2BX1 g284__2398(.AN (n_10), .B (rst_i), .Y (n_12));
  NOR2BX1 g285__5107(.AN (n_9), .B (rst_i), .Y (n_11));
  ADDFX1 g286__6260(.A (a_i[3]), .B (b_i[3]), .CI (n_6), .CO (n_9), .S
       (n_10));
  SDFFQX1 \genblk2[2].reg_s_q_o_reg (.CK (clk_i), .D (n_8), .SI
       (s_o[1]), .SE (SE), .Q (s_o[2]));
  NOR2BX1 g288__4319(.AN (n_7), .B (rst_i), .Y (n_8));
  ADDFX1 g289__8428(.A (a_i[2]), .B (b_i[2]), .CI (n_3), .CO (n_6), .S
       (n_7));
  SDFFQX1 \genblk2[1].reg_s_q_o_reg (.CK (clk_i), .D (n_5), .SI
       (s_o[0]), .SE (SE), .Q (s_o[1]));
  NOR2BX1 g291__5526(.AN (n_4), .B (rst_i), .Y (n_5));
  ADDFX1 g292__6783(.A (a_i[1]), .B (b_i[1]), .CI (n_0), .CO (n_3), .S
       (n_4));
  SDFFQX1 \genblk2[0].reg_s_q_o_reg (.CK (clk_i), .D (n_2), .SI
       (scan_in), .SE (SE), .Q (s_o[0]));
  NOR2BX1 g294__3680(.AN (n_1), .B (rst_i), .Y (n_2));
  ADDFX1 g295__1617(.A (a_i[0]), .B (b_i[0]), .CI (c_i), .CO (n_0), .S
       (n_1));
endmodule

